<!DOCTYPE html>
<html>

<head>
	<?php include 'include/head.php'; ?>
	<script type="text/javascript" src="../js/user-controller.js"></script>
	<script type="text/javascript" src="../js/character-controller.js"></script>
</head>

<body ng-app="rolApp">
	<?php include 'include/header.php'; ?>

	<div class="container">

		<div ng-controller="CharacterController" class="mt-4" ng-cloak>

			<h1>{{ 'PLAYERS.TITLE' | translate }}</h1>
			<div>
				You can manage the players here
			</div> <br>

			<div ng-if="successMsg" class="alert alert-success" role="alert">
				{{successMsg}}
			</div>
			<div ng-if="errorMsg" class="alert alert-danger" role="alert">
				{{errorMsg}}
			</div>

			<h3>{{ 'PLAYERS.LIST' | translate }}</h3>
			<br>
			<div>
				<table class="table table-sm table-bordered table-striped">
					<thead>
						<tr>
							<th scope=\"col\">{{ 'NAME' | translate }}</th>
							<th scope=\"col\">{{ 'LIFE' | translate }}</th>
							<th scope=\"col\">{{ 'MAXLIFE' | translate }}</th>
							<th scope=\"col\">{{ 'DESCRIPTION' | translate }}</th>
							<th scope=\"col\">{{ 'ATTACK' | translate }}</th>
							<th scope=\"col\">{{ 'DEFENSE' | translate }}</th>
							<th scope=\"col\">{{ 'DEXTERITY' | translate }}</th>
							<th scope=\"col\">{{ 'LEVEL' | translate }}</th>
							<th>Control</th>
							<th scope=\"col\">{{ 'OPTIONS' | translate }}</th>
						</tr>
					</thead>
					<tbody>
						<tr ng-repeat="character in characterList" ng-include="selectTemplate(character)">
						</tr>
					</tbody>
				</table>
				<script type="text/ng-template" id="display">
					<td>{{character.name}}</td>
					<td>{{character.life}} <span ng-if="character.life <= 0" class="badge badge-danger">MUERTO<i class="fas fa-skull-crossbones"></i></span></td>
					<td>{{character.maxlife}}</td>
					<td>{{character.description}}</td>
					<td>{{character.attack}}</td>
					<td>{{character.defense}}</td>
					<td>{{character.dexterity}}</td>
					<td>{{character.level}}</td>
					<td>{{character.control}}</td>
					<td class="text-nowrap">
						<button type="button" class="btn btn-primary" ng-click="edit(character)"><i class="fas fa-edit"></i></button>
						<button type="button" class="btn btn-danger" ng-click="deleteCharacter(character.name)"><i class="far fa-trash-alt"></i></button>
					</td>
				</script>
				<script type="text/ng-template" id="edit">
					<td>{{character.name}}</td>
					<td><input type="number" min="0" class="form-control" ng-model="selectedCharacter.life" /></td>
					<td><input type="number" min="1" class="form-control" ng-model="selectedCharacter.maxlife" /></td>
					<td><input type="text" class="form-control" ng-model="selectedCharacter.description" /></td>
					<td><input type="number" class="form-control" ng-model="selectedCharacter.attack" /></td>
					<td><input type="number" class="form-control" ng-model="selectedCharacter.defense" /></td>
					<td><input type="number" class="form-control" ng-model="selectedCharacter.dexterity" /></td>
					<td><input type="number" min="0" class="form-control" ng-model="selectedCharacter.level" /></td>
					<td><select class="form-control" ng-model="selectedCharacter.control" id="control" ng-options="user for user in users"></td>
					<td class="text-nowrap">
					<button type="button" class="btn btn-primary" ng-click="save(selectedCharacter)"><i class="far fa-save"></i></button>
					<button type="button" class="btn btn-secondary" ng-click="cancelEdit()"><i class="fas fa-times"></i></button>
					</td>
				</script>
			</div>

			<h3>{{ 'PLAYERS.CREATE' | translate }}</h3><br>
			<form>
				<div class="form-group row">
					<label for="name" class="col-sm-2 col-form-label">{{ 'NAME' | translate }}</label>
					<div class="col-sm-6">
						<input type="text" ng-model="pj.name" class="form-control" id="name" value="">
					</div>
					<label for="control" class="col-sm-1 col-form-label">{{ 'CONTROL' | translate }}</label>
					<div class="col-sm-3">
						<select ng-model="pj.control" class="form-control" id="control" ng-options="user for user in users">
						</select>
					</div>
				</div>
				<div class="form-group row">
					<label for="maxlife" class="col-sm-2 col-form-label">{{ 'MAXLIFE' | translate }}</label>
					<div class="col-sm-10">
						<input type="number" ng-model="pj.life" class="form-control" id="maxlife" value="">
					</div>
				</div>
				<div class="form-group row">
					<label class="col-sm-2 col-form-label">{{ 'STATISTICS' | translate }}</label>
					<div class="row col-sm-10">
						<label for="attack" class="col-sm-1 col-form-label">{{ 'ATTACK' | translate }}</label>
						<div class="col-sm-3">
							<input type="number" ng-model="pj.attack" class="form-control" id="attack" value="">
						</div>
						<label for="defense" class="col-sm-1 col-form-label">{{ 'DEFENSE' | translate }}</label>
						<div class="col-sm-3">
							<input type="number" ng-model="pj.defense" class="form-control" id="defense" value="">
						</div>
						<label for="dexterity" class="col-sm-1 col-form-label">{{ 'DEXTERITY' | translate }}</label>
						<div class="col-sm-3">
							<input type="number" ng-model="pj.dexterity" class="form-control" id="dexterity" value="">
						</div>
					</div>
				</div>
				<div class="form-group row">
					<label for="level" class="col-sm-2 col-form-label">{{ 'LEVEL' | translate }}</label>
					<div class="col-sm-10">
						<input type="number" ng-model="pj.level" class="form-control" id="level" value="">
					</div>
				</div>
				<div class="form-group row">
					<label for="description" class="col-sm-2 col-form-label">{{ 'DESCRIPTION' | translate }}</label>
					<div class="col-sm-10">
						<input type="text" ng-model="pj.description" class="form-control" id="description" value="">
					</div>
				</div>
				<button type="submit" class="btn btn-primary mb-2" ng-click="create(pj)">{{ 'CREATE' | translate }}</button>
			</form>

			<br><br>

		</div>
	</div>

</body>

</html>