<?php
use RolBot\Repository\InfoRepository;
use RolBot\Config\Configuration;

$uploadFolder = Configuration::get('folderServerPrivateUploadPath');
$infoRepository = new InfoRepository($uploadFolder);
$result = $infoRepository->uploadFileFromPost("name", "description", "fileToUpload");

$ok = $result['ok'];
$errorMessage = null;
if (!$ok && isset($result['message'])) {
	$errorMessage = $result['message'];
}
?>

<!DOCTYPE html>
<html>

<head>
<?php include 'include/head.php'; ?>
<script type="text/javascript" src="../js/info-controller.js"></script>
</head>

<body ng-app="rolApp">
<?php include 'include/header.php'; ?>

<div class="container">

<div ng-controller="InfoController" ng-cloak>
	<h1>{{ 'INFO.TITLE' | translate }}</h1>
	<div>
		{{ 'INFO.DESCRIPTION' | translate }}
	</div>
	<br><br>

	<div ng-if="successMsg" class="alert alert-success" role="alert">
		{{successMsg}}
	</div>
	<div ng-if="errorMsg" class="alert alert-danger" role="alert">
		{{errorMsg}}
	</div>

	<h3>{{ 'INFO.ACTIVELIST' | translate }}</h3>
	<br>
	<div>
		<table class="table table-sm table-bordered table-striped">
			<thead>
				<tr>
					<th scope=\"col\">{{ 'NAME' | translate }}</th>
					<th scope=\"col\">{{ 'DESCRIPTION' | translate }}</th>
					<th scope=\"col\">{{ 'FILE' | translate }}</th>
					<th scope=\"col\">{{ 'OPTIONS' | translate }}</th>
				</tr>
			</thead>
			<tbody>
				<tr ng-repeat="infoEntry in infoList">
					<td>{{infoEntry.name}}</td>
					<td>{{infoEntry.text}}</td>
					<td><a ng-href="{{infoEntry.fullPath}}">{{infoEntry.file}}</a></td>
					<td><button type="button" class="btn btn-danger" ng-click="deleteInfo(infoEntry.name)"><i class="far fa-trash-alt"></i></button></td>
				</tr>
			</tbody>
		</table>
	</div>

	<br><br>

	<form method="post" enctype="multipart/form-data" action="#">
		<h3>{{ 'CREATE' | translate }}</h3>

		<?php
	if ($errorMessage) {
		?>
				<div class="mt-3 alert alert-danger" role="alert">
				<?php echo $errorMessage; ?>
				</div>
		<?php

}
?>

		<label for="name" class="col-form-label">{{ 'INFO.NAME' | translate }}</label>
		<div class="col-sm-10">
		<input type="text" class="form-control" name="name" id="name" placeholder="nombre">
		</div>

		<label for="description" class="col-form-label">{{ 'DESCRIPTION' | translate }}</label>
		<div class="col-sm-10">
		<input type="text" class="form-control" name="description" id="description" placeholder="descripción">
		</div>

		<label for="fileToUpload" class="col-form-label">{{ 'FILE' | translate }}</label>
		<div class="col-sm-10">
		<input class="form-control-file" type="file" name="fileToUpload" id="fileToUpload">
		</div>

		<div class="mt-4 col-sm-10">
		<input type="submit" value="{{ 'CREATE' | translate }}" name="submit">

	</form>

</div>
</div>
<br><br>
</body>
</html>
