<!DOCTYPE html>
<html>

<head>
	<?php include 'include/head.php'; ?>
	<script type="text/javascript" src="../js/user-controller.js"></script>
</head>

<body ng-app="rolApp">
	<?php include 'include/header.php'; ?>

	<div class="container">

		<div ng-controller="UserController" class="mt-4" ng-cloak>

			<h1>{{ 'USERS.TITLE' | translate }}</h1>
			<div>
			{{ 'USERS.DESCRIPTION' | translate }}
			</div>
			<br>

			<div ng-if="successMsg" class="alert alert-success" role="alert">
				{{successMsg}}
			</div>
			<div ng-if="errorMsg" class="alert alert-danger" role="alert">
				{{errorMsg}}
			</div>

			<h3>{{ 'USERS.LIST' | translate }}</h3>
			<br>
			<div>
				<table class="table table-sm table-bordered table-striped">
					<thead>
						<tr>
							<th scope=\"col\">{{ 'NAME' | translate }}</th>
							<th scope=\"col\">Telegram id</th>
							<th scope=\"col\">{{ 'USERS.ISMASTER' | translate }}</th>
							<th scope=\"col\">{{ 'DESCRIPTION' | translate }}</th>
							<th scope=\"col\">{{ 'OPTIONS' | translate }}</th>
						</tr>
					</thead>
					<tbody>
						<tr ng-repeat="user in userList">
							<td>{{user.name}}</td>
							<td>{{user.userid}}</td>
							<td>{{user.ismaster ? "Yes" : "No"}}</td>
							<td>{{user.description}}</td>
							<td class="text-nowrap">
								<button type="button" class="btn btn-danger" ng-click="deleteUser(user.name)"><i class="far fa-trash-alt"></i></button>
							</td>
						</tr>
					</tbody>
				</table>
			</div>

			<h3>{{ 'USERS.CREATE' | translate }}</h3><br>
			<form>
				<div class="form-group row">
					<label for="name" class="col-sm-2 col-form-label">{{ 'NAME' | translate }}</label>
					<div class="col-sm-10">
						<input type="text" ng-model="user.name" class="form-control" id="name" value="">
					</div>
				</div>
				<div class="form-group row">
					<label for="maxlife" class="col-sm-2 col-form-label">Telegram Id</label>
					<div class="col-sm-10">
						<input type="number" ng-model="user.userid" class="form-control" id="maxlife" value="">
					</div>
				</div>
				<div class="form-group row">
					<div class="col-sm-2">{{ 'USERS.ISMASTER' | translate }}</div>
					<div class="col-sm-10">
						<div class="form-check">
							<input class="form-check-input" ng-model="user.ismaster" type="checkbox" id="gridCheck1">
						</div>
					</div>
				</div>
				<div class="form-group row">
					<label for="description" class="col-sm-2 col-form-label">{{ 'DESCRIPTION' | translate }}</label>
					<div class="col-sm-10">
						<input type="text" ng-model="user.description" class="form-control" id="name" value="">
					</div>
				</div>
				<button type="submit" class="btn btn-primary mb-2" ng-click="create(user)">{{ 'CREATE' | translate }}</button>
			</form>

			<br><br>

		</div>
	</div>

</body>

</html>